version: '3.9'

networks:
  droneapi:
    external:
      name: droneapi

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    networks:
      - droneapi
    ports:
      - "80"
      - "443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
        
  db:
    container_name: drone_db
    restart: always
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "droneapp1234"
      MSSQL_PID: "Developer"
      MSSQL_USER: "SA"
      ACCEPT_EULA: "Y"
    volumes:
      - drones_data:/var/opt/mssql
    networks:
      - droneapi 

  elasticsearch:
    container_name: elasticsearch
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - discovery.type=single-node
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - target: 9200
        published: 9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - droneapi

  kibana:
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - target: 5601
        published: 5601
    networks:
      - droneapi 
        
volumes:
  drones_data:
  elasticsearch-data:
    driver: local