version: '3.9'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/Presentation/API/Dockerfile

  arm_db:
    image: mcr.microsoft.com/azure-sql-edge

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.3