version: '3.9'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_HTTPS_PORT=8001
      # - ASPNETCORE_Kestrel_Certificates_Development_Password=P@ssword01
      # - ASPNETCORE_URLS=https://+;http://+
      - "Serilog:MinimumLevel:Default=Information"
      - "Serilog:MinimumLevel:Override:Microsoft=Information"
      - "Serilog:MinimumLevel:Override:System=Warning"
      - "ConnectionStrings:DronesAppConnectionString=Server=db;Database=DroneAppDB;User Id=sa;Password=droneapp1234;"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
      - "DroneConfiguration:MinBatteryCapacity=25"
      - "DroneConfiguration:MaxBatteryCharge=100"
      - "CacheSettings:ConnectionString=rediscache:6379"
      - "DroneBatteryLevelInterval=*/1 * * * *"
      - "RateLimiting:Limit=50"
      - "RateLimiting:Period=10m"
    ports:
      - "8000:80"
      # - "443"
    depends_on:
      - db
      - elasticsearch
      - kibana
      - rediscache
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    networks:
      - droneapi

  arm_db:
    container_name: drone_arm_db
    environment:
      MSSQL_SA_PASSWORD: "droneapp1234"
      MSSQL_PID: "Developer"
      MSSQL_USER: "SA"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - drones_arm_data:/var/opt/mssql
    networks:
      - droneapi

  # Elasticsearch
  elasticsearch:
    container_name: elasticsearch
    environment:
      #- xpack.monitoring.enabled=true
      # - xpack.watcher.enabled=false
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - "discovery.type=single-node"
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - target: 9200
        published: 9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - droneapi

  # Kibana
  kibana:
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - target: 5601
        published: 5601
    networks:
      - droneapi

  # Portainer - https://gist.github.com/deviantony/62c009b41bde5e078b1a7de9f11f5e55
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    #command: --admin-password "$(htpasswd -nb -B admin superpassword | cut -d ':' -f 2)" # admin/superpassword dronE@api_12345
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_arm_data:/data
    networks:
      - droneapi
    
  # Redis Cache
  rediscache:
    container_name: rediscache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - droneapi
        
volumes:
  drones_arm_data:
  portainer_arm_data:
  elasticsearch-data:
    driver: local

networks:
  droneapi:
    driver: bridge